### ISSUE TITLE
Add automatic link checker to osqp.org website

### ISSUE THREAD

**Issue by bstellato** [osqp/osqp#334]
It should help with issues like #329 

This should be a good option: https://github.com/filiph/linkcheck

**Comment by imciner2** [comment]
Here is an example of a link checker workflow that runs periodically: https://github.com/smartcontractkit/documentation/blob/222687e8acf6b51669724e2513ea51df32b64a19/.github/workflows/check-links.yml.

I think having a workflow like that (in addition to a build-time test) would be good so that we can catch when external links break due to external changes.
