### ISSUE TITLE
i use  two format,it may increase solve time?

### ISSUE THREAD

**Issue by longjianquan** [osqp/osqp#339]
suppose   a inequality constraint  
case1:     -1=<x<=1  (many)

case2:      99999999>=x>=-1  and       9999999>=-x>=-1   

if i have 2000 constraint  just like case1,then i write as case2. 
it will increase solve time?

**Comment by goulart-paul** [comment]
It is likely to increase the solve time, but probably not substantially.   The reason is that the `A` matrix in your constraints, which take the form `l \le Ax \le u`, will remain extremely sparse but just be twice as tall.    The factorisation time in OSQP will therefore not double in most cases, unless everything else is already extremely simple (i.e. diagonal cost, no other constraints etc).   Some other things get worse too, e.g. you will have twice as many multipliers.

Note that this sort of question might be better for the OSQP discussion forum.
