### ISSUE TITLE
release 0.6 does not support asymetric P

### ISSUE THREAD

**Issue by tmacattank** [osqp/osqp#351]
I am using OSQP for a project, the quadratic term of ojective function has an asymetric P formation, I found that release 0.6 does not support it by outputing the factorization only supports a upper triangle matrix P, while I tried relesase 0.4, it can support an asymetrix P term. Is that any way such that the latest release can support asymetric P formulation?

**Comment by imciner2** [comment]
The change to only accept the upper triangular portion of P was done on purpose. The solver requires that P is a symmetric matrix in order for it to function, and before it was just silently dropping the lower triangular portion of P and reflecting the upper triangular portion into the lower triangular portion to make a symmetric matrix - so if you were providing a non-symmetric P matrix in 0.4, it was actually not solving the problem you were expecting but instead a different one. This is now fixed in 0.6, so the solver will always solve the problem you are providing because it no longer drops part of the P matrix with no warning.
