### ISSUE TITLE
OSQP failed in mpc online running

### ISSUE THREAD

**Issue by fkshine** [osqp/osqp#364]
I want't to used osqp in solving mpc problems, but always failed during online running. 

When use other solvers, the problem has a solution ,and it convergences in a few times.
But when I use OSQP, it may need 7000 more times to get a solution。
It will return inaccurate solutions when I require more precise solution.
Here is the problems, thank you very much
[problem.zip](https://github.com/osqp/osqp/files/7674307/problem.zip)

**Comment by goulart-paul** [comment]
Your problem data is very badly conditioned in this problem.   P is a diagonal matrix whose unique non-zero entries are ~966, 1000 and 2.5e12, and the linear term is all zero.     

If I just normalize P by its largest entry the solver terminates in 50 iterations for me.   The solution appears to just be a vector in the kernel of P that also satisfies the constraints.   

You also have some huge upper bounds on some variables (1e9).   If you actually want these to be unbounded, better to set these to Inf (or OSQP_INF depending on the interface you are using).

**Comment by fkshine** [comment]
Thank you very much for your timely reply. I tried to scale the P matrix,  and the the solver get convergenced in 150 iterations, it is  amazing! 

But the solution seems different with the one with no scaling.  Is the the reason of resolution?

So what is better to be done before the problem passed to OSQP? Is it always work by scaling the P matrix? I  will always meet the badly conditioned problems
[solution.zip](https://github.com/osqp/osqp/files/7707838/solution.zip)
.

**Comment by goulart-paul** [comment]
There are several possibilities:

- Your P matrix is not positive definite, which means that the optimizer may not be unique.  I mentioned in the first reply that your optimizer is just a vector in the null space of P, so any null vector that satisfies the inequalities would be equally good.   

- You should expect your answers to potentially differ in norm by an amount up to the convergence thresholds you set (roughly speaking).

In general OSQP does a pretty good job with internal scaling and you shouldn't have to do anything special.   In your case, however, the scaling was so extreme that it was causing problems.    In general I would suggest considering carefully whether the original values you had in the cost function really constitute a sensible model for your problem, since the range of values that appear covers a range from 10^1 to about 10^12.
