### ISSUE TITLE
About cuosqp installing

### ISSUE THREAD

**Issue by XinchenDengll** [osqp/osqp#403]
I want to use OSQP with CUDA. I cant install it successfully.
I run the code in https://github.com/osqp/cuosqp as follows:

git clone --recurse-submodules https://github.com/oxfordcontrol/cuosqp
cd cuosqp
python setup.py install

Here will be 
![1647179800(1)](https://user-images.githubusercontent.com/53013199/158062931-998271b0-1cb5-4197-b7f8-c45a25f49512.jpg)
![image](https://user-images.githubusercontent.com/53013199/158062952-a69d7650-88fd-424b-8d92-69db7175c5fc.png)

Looking forward to your help!!

**Comment by imciner2** [comment]
cuOSQP has now been integrated into the main OSQP repository as the cuda backend. It can be used by doing `cmake -DOSQP_ALGEBRA_BACKEND=cuda` during the configuration, and then compiling user programs linking to OSQP as normal.

**Comment by CebFu** [comment]
> cuOSQP has now been integrated into the main OSQP repository as the cuda backend

Howerver, I installed osqp by ‘pip’ or ‘conda’。 neither has the 'cuda pcg' solver. what should I do? thanks

**Comment by vineetbansal** [comment]
Hi @CebFu - we're currently not distributing the wheels for `osqp-cuda` on pypi, but you should be able to build cuda support for `osqp` on your platform as long as you have cudatoolkit installed. Look at the instructions here (The "Wrappers for CUDA" section).

https://osqp.org/docs/contributing/python.html

Let us know if you think we can expand on the instructions further.

**Comment by CebFu** [comment]
Hello, @vineetbansal - Thanks for your reply. I have installed it. However,  I tested it for an unconstrained problem, the result was not satisfactory. It doesn't seem to be converging, and it's not very efficient. Is there a more efficient way to run unconstrained problems? Or providing a linear solver interface. Thanks very much.
Best wishes
Ceb

**Comment by vineetbansal** [comment]
@CebFu - are you saying that you're getting different results when using `problem.solve()` (where `problem` is a python `osqp.OSQP` object), when you instantiate it using `prob = osqp.OSQP(algebra='builtin')` vs `prob = osqp.OSQP(algebra='cuda')` ? That's the way one would switch the backend algebras in python.

Just trying to understand the issue here - different behaviors depending on different algebra backends is not unexpected, both both should give you satisfactory results, or you may have to tweak the parameters to the constructor.
