### ISSUE TITLE
Different internal flow of osqp_update_bounds and  osqp_update_lower_bounds/osqp_update_upper_bounds

### ISSUE THREAD

**Issue by DanEla22** [osqp/osqp#404]
Hi,

I ran into some questions regarding the public api functions to update the bounds. When calling osqp_update_lower/upper the internal flow is different from the one inside osqp_update_bounds().

Steps in osqp_update_bounds()

1) Check if lower bound is smaller than upper bound --> otherwise return 1
2) Replace l and u by the new vectors --> update work-> data

Steps in osqp_update_lower_bound() and osqp_update_upper_bound()

1) Replace l and u by the new vectors --> update work-> data
2) Check if lower bound is smaller than upper bound --> otherwise return 1

This seems to be a little bit inconsistent, is there a concept of how to handle errors during updating the values? Or to be more specific should the OSQPData inside the workspace always be valid, since possible ill-posed data is caught before updating?

Thanks.

**Comment by imciner2** [comment]
Good catch. yes, the workspace should in general have valid data at all times so that you can call the solver and have it properly operate. We have actually combined all these functions together for the 1.0 version we are currently developing, and it will check the validity of the data before updating the workspace with the new vectors (so it will ensure the lower bounds are actually lower than the upper bounds before accepting them).
