### ISSUE TITLE
Manual, full warm starting 

### ISSUE THREAD

**Issue by 4estlaine** [osqp/osqp#416]
Is there a way to fully warm-start the solver using a fresh model?

Specifically, this is my setup (working in Julia).

```julia
function test(P,q,A,l,u)
  m1 = OSQP.model()
  OSQP.setup!(m; P=P, q=q, A=A, l=l, u=u, polish=false)
  results_A = OSQP.solve!(m)
  num_iters = results_A.info.iters
  
  m2 = OSQP.model()
  local results_B
  OSQP.setup!(m; P=P, q=q, A=A, l=l, u=u, polish=false, max_iter=1)
  for iter in 1:num_iters
    results_B = OSQP.solve!(m)
  end

  @assert isapprox(results_A.x, results_B.x)
end
```

The above code works ( assert passes ). However, I have an application in which I need to be able to do something like the following:

```julia
function test(P,q,A,l,u)
  m1 = OSQP.model()
  x = zeros(Float64, length(q))
  y = zeros(Float64, ength(l))
  OSQP.setup!(m; P=P, q=q, A=A, l=l, u=u, polish=false, rho=rho)
  OSQP.warm_start!(m; x=x, y=y)
  results_A = OSQP.solve!(m)
  num_iters = results_A.info.iters
  
  m2 = OSQP.model()
  local results_B
  rho = 0.1
  x = zeros(Float64, length(q))
  y = zeros(Float64, ength(l))
  
  for iter in 1:num_iters
    OSQP.setup!(m; P=P, q=q, A=A, l=l, u=u, polish=false, max_iter=1, rho=rho)
    OSQP.warm_start!(m; x=x, y=y)
    results_B = OSQP.solve!(m)
    rho = results.info.rho_estimate
    x = results.x
    y = results.y
  end

  @assert isapprox(results_A.x, results_B.x)
end
```

This second version does not work. Basically, it seems there is some other internal state that is held in the OSQP model, which cannot be warm-started manually. Am I doing this incorrectly, or is what I am after (exact warm-start using a fresh model) not possible? Thanks in advance!

**Comment by goulart-paul** [comment]
Aside from the primal and dual variables the only other internal state is the iteration count, which determines when convergence checks or refactorizations are triggered.  You could potentially see differences in behaviour in situations where the \rho parameter is to be updated, since the solver might trigger updates at different iteration numbers if you run the solver the way you are doing here.

That said, I think you just have a bug in your code.   The code posted didn't work for me, but the following does:

```julia
using SparseArrays, LinearAlgebra, OSQP

# example problem data
A = SparseMatrixCSC(I(3))
A = [A;-A]
l = -ones(6)
u =  ones(6)
P = SparseMatrixCSC(I(3))
q = [1.,1.,1.]


function test1(P,q,A,l,u)
  m1 = OSQP.Model()
  OSQP.setup!(m1; P=P, q=q, A=A, l=l, u=u, polish=false)
  results_A = OSQP.solve!(m1)
  num_iters = results_A.info.iter

  m2 = OSQP.Model()
  local results_B
  OSQP.setup!(m2; P=P, q=q, A=A, l=l, u=u, polish=false, max_iter=1)
  for iter in 1:num_iters
    results_B = OSQP.solve!(m2)
  end

  @assert isapprox(results_A.x, results_B.x)
  println("Method 1 works")
end

function test2(P,q,A,l,u)
  m1 = OSQP.Model()

  OSQP.setup!(m1; P=P, q=q, A=A, l=l, u=u, polish=false)
  results_A = OSQP.solve!(m1)
  num_iters = results_A.info.iter

  m2 = OSQP.Model()
  local results_B
  rho = 0.1
  x = zeros(Float64, length(q))
  y = zeros(Float64, length(l))
  OSQP.setup!(m2; P=P, q=q, A=A, l=l, u=u, polish=false, max_iter=1, rho=rho)
  for iter in 1:num_iters
    results_B = OSQP.solve!(m2)
  end

  @assert isapprox(results_A.x, results_B.x)
println("Method 2 works")
end


test1(P,q,A,l,u)
test2(P,q,A,l,u)
```

Note that if you are using Julia exclusively (and not doing codegen or something) then you might like to use the [COSMO](https://oxfordcontrol.github.io/COSMO.jl/stable/) solver instead.   For QP problems it uses the same underlying algorithm as OSQP, but we have added some additional acceleration methods that might give a performance boost.   Those methods may appear in OSQP eventually, but not anytime soon.

**Comment by 4estlaine** [comment]
Thanks for the pointer about COSMO, I will definitely give that a try. Per the code here, unfortunately the fix you made (as I see it) made version A and B the same. The point of version B was to create a new OSQP model and initialize it at every iteration of the loop. With the changes you made, the only difference between A and B is that B is initialized with rho=0.1, but that is the default value anyways. 

Your pointer about the rho updates is a good one though, I will play around with ways of constraining the rho updates to see if that works.

**Comment by goulart-paul** [comment]
Very sorry about that.   I think I fixed the problem there by just copy-pasting the same thing twice, which is probably not the insight you were looking for.

Let me try this again.   I think what you are trying to do is this:
```julia

using SparseArrays, LinearAlgebra, OSQP

# example problem data
A = SparseMatrixCSC(I(3));
A = [A;-A]
l = -ones(6)
u =  ones(6)
P = SparseMatrixCSC(I(3))
q = [1.,1.,1.]


function test1(P,q,A,l,u)
  m1 = OSQP.Model()
  OSQP.setup!(m1; P=P, q=q, A=A, l=l, u=u, polish=false)
  results_A = OSQP.solve!(m1)
  num_iters = results_A.info.iter

  m2 = OSQP.Model()
  local results_B
  OSQP.setup!(m2; P=P, q=q, A=A, l=l, u=u, polish=false, max_iter=1)
  for iter in 1:num_iters
    results_B = OSQP.solve!(m2)
  end

  @assert isapprox(results_A.x, results_B.x)
end

function test2(P,q,A,l,u)
  m1 = OSQP.Model()
  x = zeros(Float64, length(q))
  y = zeros(Float64, length(l))
  OSQP.setup!(m1; P=P, q=q, A=A, l=l, u=u, polish=false)
  OSQP.warm_start!(m1; x=x, y=y)
  results_A = OSQP.solve!(m1)
  num_iters = results_A.info.iter

  m2 = OSQP.Model()
  local results_B
  rho = 0.1
  x = zeros(Float64, length(q))
  y = zeros(Float64, length(l))

  for iter in 1:num_iters
    OSQP.setup!(m2; P=P, q=q, A=A, l=l, u=u, polish=false, max_iter=1, rho=rho)
    OSQP.warm_start!(m2; x=x, y=y)
    results_B = OSQP.solve!(m2)
    rho = results_B.info.rho_estimate
    x = results_B.x
    y = results_B.y
  end


  println("results_A.x",results_A.x)
  println("results_B.x",results_B.x)
  @assert isapprox(results_A.x, results_B.x)
end


test1(P,q,A,l,u)
test2(P,q,A,l,u)
```

I see that the assertion in the second case fails here.   I think the reason is that there is a misunderstanding about this line : 
```julia 
rho = results_B.info.rho_estimate
```

The value returned there is just whatever the solver thinks *would have been* the best choice of `rho`.   It is not the value that it actually used.   It might not use that value either because 1) it didn't meet the iteration threshold required before updating, or 2) The difference between the best guess rho and the one being used are not sufficiently different.   You are using only 1 iteration per pass, so are getting the first of these cases.
 
The effect of the implementation above is that the solver is being rebuilt at every iteration and initialized with the best guess `rho` from the previous one, i.e. the update interval is 1 and no tolerance test is applied.   This will be computationally super expensive because every rho update will force a KKT refactor.     It also tends to lead to solver instability in some cases because it takes a few iterations for that estimate to settle, and making a premature update will get you stuck with a bad value (usually very large or small) from which the solver can't recover.

As far as I can see we don't report the value of rho that is actually used in the solver, only the number of updates (in `results.info.rho_updates`), although you can at least see it reported in the final column of the verbose output.   This seems like an oversight to me.    If the above makes sense, then you could perhaps report it as a separate issue.

**Comment by 4estlaine** [comment]
Thank you for your help on this! I will consider a separate issue/pull request to expose the used value of rho.
