### ISSUE TITLE
Changing Verbosity Changes the Solution

### ISSUE THREAD

**Issue by lkavlie** [osqp/osqp#468]
When running the osqp Python interface in with version 0.6.2, you get different answer when you run in verbose mode vs non-verbose mode. See the following example modified from [the osqp examples](https://osqp.org/docs/examples/setup-and-solve.html):

```
import osqp
import numpy as np
from scipy import sparse

P = sparse.csc_matrix([[4, 1], [1, 2]])
q = np.array([1, 1])
A = sparse.csc_matrix([[1, 1], [1, 0], [0, 1]])
l = np.array([1, 0, 0])
u = np.array([1, 0.7, 0.7])

prob = osqp.OSQP()
prob.setup(P, q, A, l, u, alpha=1.0, verbose=True)
x_verbose = prob.solve().x

prob = osqp.OSQP()
prob.setup(P, q, A, l, u, alpha=1.0, verbose=False)
x_terse = prob.solve().x

print('-'*80)
print('verbose x = ', x_verbose)
print('terse x = ', x_terse)

print('verbose A*x = ', A * x_verbose)
print('terse A*x = ', A * x_terse)
```

Running this code gives the following output:

```
--------------------------------------------------------------------------------
verbose x =  [0.30000019 0.69999981]
terse x =  [0.29877108 0.701228  ]
verbose A*x =  [1.         0.30000019 0.69999981]
terse A*x =  [0.99999908 0.29877108 0.701228  ]
```

Note how the non-verbose solution doesn't even satisfy the constraints of the problem. Is there something wrong with my assumptions about verbose vs non-verbose? Thanks!

**Comment by lkavlie** [comment]
After doing a little more testing, it appears the problem is more an issue of inconsistency. Sometimes the answers agree, and sometimes they don't. For example, consider the following re-wrapped code:

```
import osqp
import numpy as np
from scipy import sparse

P = sparse.csc_matrix([[4, 1], [1, 2]])
q = np.array([1, 1])
A = sparse.csc_matrix([[1, 1], [1, 0], [0, 1]])
l = np.array([1, 0, 0])
u = np.array([1, 0.7, 0.7])

def f(verbose):
  prob = osqp.OSQP()
  prob.setup(P, q, A, l, u, alpha=1.0, verbose=verbose)
  x = prob.solve().x
  return x

s = set()
for i in range(2000):
  s.add(tuple(f(False)))
for item in s:
  print(item)
```

This gives the output:

```
(0.300000191114193, 0.6999998090276102)
(0.2987710845986425, 0.7012279955440646)
```

I did NOT get similar behavior when I used set verbose=True.

**Comment by goulart-paul** [comment]
I think that the issue is not directly related to the verbosity, but rather to the way that internal refactorizations are computed based on the relative times required to factor and solve the KKT system.

The code makes an initial KKT factorization and captures the time taken to do so.   It then iterates until the total iteration time hits some fraction of the initial factorization time, then it refactors (this is the "rho update" step).

I could imagine that print statements could be messing with that estimate.   They're not supposed to be timed, but they're sort of hard to eliminate completely.   That would cause refactorizations to trigger at different points.

To confirm, you could tell the solver to update based on a fixed number of iterations rather than a fraction of the solve time.   You want to trigger off of `adaptive_rho_interval` instead of `adaptive_rho_fraction`.   See here : https://osqp.org/docs/interfaces/solver_settings.html

Regarding the accuracy :  the solver is giving you a solution to within the tolerance you requested, which may or may not be strictly inside the constraints.    It's natural to ask why it doesn't just round the values up or down, but the solver doesn't make a distinction between interval constraints $l \le x \le u$ and more general ones $l \le Ax \le u$.   The former is easy to 
round, but the latter is not.    If you know that some of your variables live on intervals then you will need to do a post-solve step to fix them to within their bounds.

**Comment by lkavlie** [comment]
Thanks for the explanation. Using adaptive_rho_interval does enforce deterministic behavior. And I understand that both solutions are reasonable. I appreciate the timely response!

**Comment by yeasmin62** [comment]
Hi, I am using the osqp version 0.6.5 and I am getting different results for the verbosity change for the solution of my problems. Is this because of the same problem explained by goulart-paul?


Thank you very much in advance.

**Comment by goulart-paul** [comment]
Quite likely, yes.
