### ISSUE TITLE
csc_spalloc and csc_spfree replacement for osqp 1.0 ?

### ISSUE THREAD

**Issue by traversaro** [osqp/osqp#576]
Hello everyone! In osqp-eigen, we have being using the csc_spalloc  and csc_spfree functions. However, in OSQP 1.0 this functions are now private. What do you suggest to use in their place? If the suggestion is just to use the code in csc_spalloc in downstream projects where csc_spalloc was called with osqp 0.6, could you consider releasing just the source code of csc_spalloc and csc_spfree  under CC0, to avoid creating confusion on the license of the copied code? Thanks! 

fyi @gergondet @giulioromualdi

See https://github.com/robotology/osqp-eigen/issues/146 for the downstream issue.

**Comment by imciner2** [comment]
`csc_spalloc` and `csc_spfree` are part of the algebra backend, which means their implementation is specific to the algebra backed used (and in fact, CUDA doesn't even have these functions because it is implemented differently), hence why they are private. Why do you need to allocate the vectors you are using in the CSC matrix everytime? The way the setup function works is OSQP takes a copy of the data from the CSC matrix and stores it in the internal data cache/workspace, so we never modify the data passed in, and the lifetime of the CSC vectors just has to be until the end of `osqp_setup`. Therefore, the expected pattern is just to allocate your own `OSQPCscMatrix` and then use `csc_set_data` with the pointers to the existing data you want to use (since you have probably already built the matrix components).

(the naming of `csc_set_data` is a bit unfortunate, and I really think we should prefix it as `OSQPCscMatrix_set_data()` actually, to avoid possible namespace collisions).

> under CC0, to avoid creating confusion on the license of the copied code?

CC0 is actually a bad license to use for code included alongside other FOSS-licensed code, since it is increasingly not considered FOSS, e.g. https://opensource.org/faq/#cc-zero and https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/message/RRYM3CLYJYW64VSQIXY6IF3TCDZGS6LM/,

**Comment by traversaro** [comment]
Thanks for the feedback, we did a problem migration of osqp-eigen to support (also, the suggested version is still released one) osqp `master` branch in https://github.com/robotology/osqp-eigen/pull/163 .
